n = input('Digite algo: ')
print('\033[31;40mO tipo primitivo de {} é {}'.format(n, type(n)))
print('a variavel {} é alfabetica? {}'.format(n, n.isalpha()))
print('a variavel {} é alfanumerica? {}'.format(n, n.isalnum()))
print('a variavel {} é um espaço? {}'.format(n, n.isspace()))
print('a variavel {} está capitalizada? {}'.format(n, n.istitle()))
print('a variavel {} é da tabela ascii? {}'.format(n, n.isascii()))
print('a variavel {} é completamente em minúscula? {}'.format(n, n.islower()))
print('a variavel {} é um número que pode ser impresso? {}'.format(n, n.isprintable()))
print('a variavel {} é um digito? {}\033[m'.format(n, n.isdigit()))
